[lint]
select = ["ALL"]
ignore = [
    "N818",
    "D100",
    "N802",
    "D104",
    "D101",
    "I001",
    "I002",
    "TRY301",
    "TRY300",
    "INP001",
    "CPY001",
    "PLR0917",
]
exclude = [
    "test/*",
]

[lint.per-file-ignores]
"app/**" = [
    "TC001",
    "TC002",
    "ARG002",
    "BLE001"
]
"app/console/commands/**" = [
    "RUF012",
]
"app/models/**" = [
    "FBT003",
    "RUF012",
]
"app/http/schemas/constraints/**" = [
    "ARG002",
    "PLR2004",
]
"database/**" = [
    "E501",
    "S608",
]
"orionis/database/**" = [
    "S608",
]
"tests/**" = [
    "ANN001",
    "ANN201",
    "ANN202",
    "PT009",
    "PT027",
    "SLF001",
    "ARG003",
    "FBT003",
    "PTH110",
    "PTH113",
    "PTH118",
    "PTH123",
    "PLC0415",
    "PLR2004",
    "DTZ001",
    "ERA001",
    "S324",
]

[lint.pydocstyle]
convention = "numpy"