import re
from pathlib import Path
from orionis.console.base.command import BaseCommand
from orionis.console.commands.support._clear import clear_files
from orionis.console.output.console import Console
from orionis.foundation.contracts.application import IApplication
from orionis.logging.contracts.logger import ILogger

def _clear_configured_log(path_template: str, base_path: Path) -> tuple[int, list[str]]:
    """
    Remove files matching one configured log path template.

    Parameters
    ----------
    path_template : str
        Log path declared by a logging channel.
    base_path : Path
        Application root for relative paths.

    Returns
    -------
    tuple[int, list[str]]
        Number of files removed and filesystem errors encountered.
    """
    target = Path(path_template)
    if not target.is_absolute():
        target = base_path / target
    directory = target.parent
    if "{suffix}" in str(directory):
        return 0, [f"Cannot clear a log path with a dynamic directory: {target}"]
    if not directory.is_dir():
        return 0, []

    pattern = re.compile(
        re.escape(target.name).replace(r"\{suffix\}", r".+") + r"(?:\.gz)?",
    )
    removed_count = 0
    errors: list[str] = []
    try:
        for candidate in directory.iterdir():
            if pattern.fullmatch(candidate.name) is None or not candidate.is_file():
                continue
            try:
                candidate.unlink()
            except FileNotFoundError:
                continue
            except OSError as error:
                errors.append(f"{candidate}: {error}")
            else:
                removed_count += 1
    except OSError as error:
        errors.append(f"{directory}: {error}")
    return removed_count, errors

class ClearLogsCommand(BaseCommand):
    """Remove files generated by the application's logging channels."""

    # ruff: noqa: TC001

    timestamps: bool = False
    signature: str = "clear:logs"
    description: str = "Clear framework log files."

    def handle( # NOSONAR
        self,
        app: IApplication,
        console: Console,
        logger: ILogger,
    ) -> int:
        """
        Remove framework log files and compressed rotated logs.

        Parameters
        ----------
        app : IApplication
            Application providing the log directory and channel paths.
        console : Console
            Console used to report the cleanup result.
        logger : ILogger
            Framework logger whose open files must be released.

        Returns
        -------
        int
            Zero when every log is removed; one when removal fails.
        """
        logger.close()
        directory = app.path("storage_logs")
        removed_count, errors = clear_files(directory, (".log", ".log.gz"))

        channels = app.config("logging.channels")
        if isinstance(channels, dict):
            log_root = directory.resolve()
            configured_paths: set[str] = set()
            for channel in channels.values():
                if not isinstance(channel, dict):
                    continue
                path_template = channel.get("path")
                if (
                    not isinstance(path_template, str)
                    or path_template in configured_paths
                ):
                    continue
                configured_paths.add(path_template)
                target = Path(path_template)
                if not target.is_absolute():
                    target = app.basePath / target
                if target.resolve().is_relative_to(log_root):
                    continue
                count, path_errors = _clear_configured_log(
                    path_template,
                    app.basePath,
                )
                removed_count += count
                errors.extend(path_errors)

        console.info(
            f"Framework logs cleared ({removed_count} file(s)).",
            timestamp=False,
        )
        for error in errors:
            console.error(error, timestamp=False)
        return int(bool(errors))
