import shutil
import sys
from pathlib import Path
from orionis.console.base.command import BaseCommand
from orionis.console.output.console import Console
from orionis.foundation.contracts.application import IApplication

_VENV_DIR_NAMES: frozenset[str] = frozenset(
    {".venv", "venv", "env", ".env", "virtualenv"},
)
_ACTIVE_VENV_BASENAME: str = (
    Path(sys.prefix).name if sys.prefix != sys.base_prefix else ""
)
_SKIP_DIRS: frozenset[str] = _VENV_DIR_NAMES | frozenset(
    {
        ".git",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        "build",
        "dist",
        "node_modules",
    },
)
if _ACTIVE_VENV_BASENAME:
    _SKIP_DIRS |= frozenset({_ACTIVE_VENV_BASENAME})
_BUILD_DIR_NAMES: tuple[str, ...] = ("build", "dist")
_COMPILED_CACHE_FILES: tuple[str, ...] = ("config", "commands", "routes")
_BYTECODE_SUFFIXES: frozenset[str] = frozenset({".pyc", ".pyo"})


class OptimizeClearCommand(BaseCommand):
    """Remove generated optimization artifacts from the application."""

    # ruff: noqa: TC001

    timestamps: bool = True
    signature: str = "optimize:clear"
    description: str = (
        "Removes compiled configuration, route, and command caches, "
        "Python bytecode, and build artifacts."
    )

    def handle(
        self,
        app: IApplication,
        console: Console,
    ) -> int:
        """
        Clear generated bytecode, build artifacts, and compiled caches.

        Parameters
        ----------
        app : IApplication
            Application providing the project and cache paths.
        console : Console
            Console used to report cleanup results and failures.

        Returns
        -------
        int
            Zero when every cleanup succeeds; one when a path cannot be removed.
        """
        base_path = app.basePath
        bytecode_count, bytecode_errors = self.__clearBytecode(base_path)
        artifact_count, artifact_errors = self.__clearBuildArtifacts(base_path)
        cache_count, cache_errors = self.__clearCompiledCaches(app)

        self.__reportCleanup(
            console,
            "Python bytecode",
            bytecode_count,
            bytecode_errors,
        )
        self.__reportCleanup(
            console,
            "Build artifacts",
            artifact_count,
            artifact_errors,
        )
        self.__reportCleanup(
            console,
            "Compiled configuration, command, and route caches",
            cache_count,
            cache_errors,
        )
        return int(bool(bytecode_errors or artifact_errors or cache_errors))

    def __clearBytecode(self, base_path: Path) -> tuple[int, list[str]]:
        """
        Remove bytecode directories and standalone bytecode files.

        Parameters
        ----------
        base_path : Path
            Root directory walked while virtual environments are excluded.

        Returns
        -------
        tuple[int, list[str]]
            Number of removed paths and filesystem errors encountered.
        """
        removed_count = 0
        errors: list[str] = []

        for root, directories, filenames in base_path.walk(
            top_down=True,
            on_error=lambda error: errors.append(str(error)),
        ):
            directories[:] = [name for name in directories if name not in _SKIP_DIRS]
            if "__pycache__" in directories:
                cache_directory = root / "__pycache__"
                if self.__removePath(cache_directory, errors):
                    removed_count += 1
                directories.remove("__pycache__")

            for filename in filenames:
                if Path(
                    filename,
                ).suffix.lower() in _BYTECODE_SUFFIXES and self.__removePath(
                    root / filename,
                    errors,
                ):
                    removed_count += 1

        return removed_count, errors

    def __clearBuildArtifacts(self, base_path: Path) -> tuple[int, list[str]]:
        """
        Remove top-level build output and package metadata directories.

        Parameters
        ----------
        base_path : Path
            Application root containing generated build artifacts.

        Returns
        -------
        tuple[int, list[str]]
            Number of removed paths and filesystem errors encountered.
        """
        errors: list[str] = []
        artifact_paths = [base_path / name for name in _BUILD_DIR_NAMES]
        artifact_paths.extend(base_path.glob("*.egg-info"))
        removed_count = 0

        for artifact_path in dict.fromkeys(artifact_paths):
            if self.__removePath(artifact_path, errors):
                removed_count += 1

        return removed_count, errors

    def __clearCompiledCaches(
        self,
        app: IApplication,
    ) -> tuple[int, list[str]]:
        """
        Remove framework-owned compiled state cache files.

        Parameters
        ----------
        app : IApplication
            Application providing the configured compiled cache path.

        Returns
        -------
        tuple[int, list[str]]
            Number of removed cache files and filesystem errors encountered.
        """
        cache_path = app.compiledPath
        if cache_path is None:
            cache_path = app.path("storage_framework") / "cache"

        errors: list[str] = []
        removed_count = 0
        for filename in _COMPILED_CACHE_FILES:
            if self.__removePath(cache_path / filename, errors):
                removed_count += 1

        return removed_count, errors

    def __removePath(self, path: Path, errors: list[str]) -> bool:
        """
        Remove one file, directory, or symbolic link and record failures.

        Parameters
        ----------
        path : Path
            Filesystem path to remove.
        errors : list[str]
            List updated with a description when removal fails.

        Returns
        -------
        bool
            Whether an existing path was removed successfully.
        """
        try:
            if path.is_symlink() or not path.is_dir():
                path.unlink()
            else:
                shutil.rmtree(path)
        except FileNotFoundError:
            return False
        except OSError as error:
            errors.append(f"{path}: {error}")
            return False
        else:
            return True

    def __reportCleanup(
        self,
        console: Console,
        label: str,
        removed_count: int,
        errors: list[str],
    ) -> None:
        """
        Write a cleanup summary and any filesystem errors to the console.

        Parameters
        ----------
        console : Console
            Console used to display the summary and errors.
        label : str
            Name of the cleanup group.
        removed_count : int
            Number of paths successfully removed.
        errors : list[str]
            Filesystem errors encountered by the cleanup group.

        Returns
        -------
        None
            Write the cleanup details to the console.
        """
        console.info(
            f"{label} cleanup removed {removed_count} item(s).",
            timestamp=False,
        )
        for error in errors:
            console.error(error, timestamp=False)
