from __future__ import annotations
import uuid
from copy import deepcopy
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any, ClassVar
from orionis.orm.attributes import AttributesMixin, serialize_for_storage
from orionis.orm.events import EventsMixin
from orionis.orm.metaclass import ModelMeta
from orionis.orm.query.builder import ModelQueryBuilder
from orionis.orm.query.expressions import (
    DeletePlan,
    InsertPlan,
    UpdatePlan,
    WhereClause,
)
from orionis.orm.relations.mixin import RelationsMixin
from orionis.orm.resolver import ConnectionResolver
from orionis.orm.soft_deletes import SoftDeletesMixin
from orionis.orm.state import StateMixin

if TYPE_CHECKING:
    from collections.abc import Callable
    from orionis.database.contracts.connection import IConnection
    from orionis.orm.collections.paginator import Paginator  # noqa: F401
    from orionis.orm.metaclass import ModelMetadata
    from orionis.orm.schema.table import TableDefinition
    from orionis.support.types.collection import Collection

# Instance slots managed directly by the model machinery.
_INTERNAL_ATTRIBUTES: frozenset[str] = frozenset({
    "_attributes",
    "_changes",
    "_exists",
    "_original",
    "_relations",
})

class Model(
    AttributesMixin,
    StateMixin,
    RelationsMixin,
    EventsMixin,
    SoftDeletesMixin,
    metaclass=ModelMeta,
):
    """
    Base class of the Orionis active-record models.

    Concrete models declare their columns with the fluent schema types
    and interact with the database exclusively through the Orionis query
    builder; the underlying SQL engine never surfaces. Class-level entry
    points such as ``where`` or ``orderBy`` start a builder implicitly.
    """

    __abstract__ = True
    __slots__ = ("_attributes", "_changes", "_exists", "_original", "_relations")

    # ── Declarative configuration ───────────────────────────────────────────

    # Logical table name; derived from the class name when None.
    table: ClassVar[str | None] = None

    # Versioned table definition shared with schema migrations.
    table_definition: ClassVar[TableDefinition | None] = None

    # Named connection; the default connection is used when None.
    connection: ClassVar[str | None] = None

    # Mass assignment whitelist; every column is fillable when empty.
    fillable: ClassVar[list[str]] = []

    # Mass assignment blacklist; supports the "*" wildcard.
    guarded: ClassVar[list[str]] = []

    # Attributes omitted from serialization.
    hidden: ClassVar[list[str]] = []

    # Attribute casts applied on hydration and assignment.
    casts: ClassVar[dict[str, str]] = {}

    # Primary key name; discovered from column flags when None.
    primary_key: ClassVar[str | None] = None

    # Whether the primary key is generated by the database.
    incrementing: ClassVar[bool] = True

    # Whether creation/update timestamps are maintained automatically.
    timestamps: ClassVar[bool] = True

    # Whether deletes stamp a column instead of removing the row.
    soft_deletes: ClassVar[bool] = False

    # Whether the primary key is a client-generated unique identifier.
    uuids: ClassVar[bool] = False

    # Accessor-backed attributes added to the serialized output.
    appends: ClassVar[list[str]] = []

    # Timestamp column names, overridable per model.
    CREATED_AT: ClassVar[str] = "created_at"
    UPDATED_AT: ClassVar[str] = "updated_at"
    DELETED_AT: ClassVar[str] = "deleted_at"

    # Metadata attached by the metaclass.
    __meta__: ClassVar[ModelMetadata | None]

    def __init__(self, attributes: dict[str, Any] | None = None) -> None:
        """
        Initialize a new, unsaved model instance.

        Parameters
        ----------
        attributes : dict or None, optional
            Attributes to mass assign honoring the fillable rules.

        Returns
        -------
        None
            This method does not return a value.

        Raises
        ------
        MassAssignmentException
            If an attribute violates the mass assignment rules.
        """
        object.__setattr__(self, "_attributes", {})
        object.__setattr__(self, "_original", {})
        object.__setattr__(self, "_changes", {})
        object.__setattr__(self, "_exists", False)
        object.__setattr__(self, "_relations", {})
        if attributes:
            self.fill(attributes)

    # ── Attribute access ────────────────────────────────────────────────────

    def __getattr__(self, key: str) -> Any:  # noqa: ANN401
        """
        Serve column values and accessor-backed attributes.

        Parameters
        ----------
        key : str
            Attribute name being accessed.

        Returns
        -------
        Any
            Attribute value; ``None`` for declared but unloaded columns.

        Raises
        ------
        AttributeError
            If the name is neither loaded, a declared column, nor an
            accessor-backed attribute.
        """
        # Internal names reaching here mean the instance is mid-construction.
        if key.startswith("_"):
            error_msg = (
                f"'{type(self).__name__}' object has no attribute '{key}'"
            )
            raise AttributeError(error_msg)

        meta = type(self).__meta__
        if meta is not None and key in meta.accessors:
            return self.getAttribute(key)

        attributes = self._attributes
        if key in attributes:
            return attributes[key]

        if meta is not None and key in meta.columns:
            return None

        error_msg = (
            f"'{type(self).__name__}' object has no attribute '{key}'"
        )
        raise AttributeError(error_msg)

    def __setattr__(self, key: str, value: Any) -> None:  # noqa: ANN401
        """
        Route column assignments into the attribute store.

        Parameters
        ----------
        key : str
            Attribute name being assigned.
        value : Any
            Value to assign.

        Returns
        -------
        None
            This method does not return a value.
        """
        if key in _INTERNAL_ATTRIBUTES:
            object.__setattr__(self, key, value)
            return

        meta = type(self).__meta__
        if meta is not None and (key in meta.columns or key in meta.mutators):
            self.setAttribute(key, value)
            return

        object.__setattr__(self, key, value)

    def __repr__(self) -> str:
        """
        Return a concise developer representation of the model.

        Returns
        -------
        str
            Representation including the class name and primary key.
        """
        meta = type(self).__meta__
        key = meta.primary_key if meta is not None else "id"
        return (
            f"<{type(self).__name__} {key}={self._attributes.get(key)!r}>"
        )

    # ── Hydration ───────────────────────────────────────────────────────────

    @classmethod
    def _newFromDatabase(cls, row: dict[str, Any]) -> Model:
        """
        Hydrate a model instance from a database row.

        Parameters
        ----------
        row : dict
            Raw row values keyed by column name. The mapping is not
            shared with any other caller, so it is adopted and mutated
            in place instead of being copied.

        Returns
        -------
        Model
            Existing model instance with casts applied.
        """
        instance = cls.__new__(cls)
        attributes = cls.__meta__.applyCasts(row)
        object.__setattr__(instance, "_attributes", attributes)
        object.__setattr__(instance, "_original", deepcopy(attributes))
        object.__setattr__(instance, "_changes", {})
        object.__setattr__(instance, "_exists", True)
        object.__setattr__(instance, "_relations", {})
        return instance

    # ── Query entry points ──────────────────────────────────────────────────

    @classmethod
    def query(cls) -> ModelQueryBuilder[Any]:
        """
        Start a new query builder bound to this model.

        Returns
        -------
        ModelQueryBuilder
            Fresh builder targeting the model table.
        """
        return ModelQueryBuilder(cls)

    @classmethod
    def getConnection(cls) -> IConnection:
        """
        Resolve the connection configured for this model.

        Returns
        -------
        IConnection
            Connection used for model queries and persistence.

        Raises
        ------
        OrmConfigurationException
            If no connection manager has been installed.
        ConnectionNotFoundException
            If the configured connection is not declared.
        """
        return ConnectionResolver.connection(cls.__meta__.connection)

    @classmethod
    def addGlobalScope(
        cls,
        name: str,
        scope: Callable[[ModelQueryBuilder[Any]], None],
    ) -> type[Model]:
        """
        Register a constraint applied to every query of this model.

        Parameters
        ----------
        name : str
            Name the scope is registered under, used to disable it later
            with ``withoutGlobalScope``.
        scope : Callable
            Callable receiving the builder and constraining it in place.

        Returns
        -------
        type
            The model class, enabling fluent chaining.
        """
        cls.__meta__.global_scopes[name] = scope
        return cls

    @classmethod
    def removeGlobalScope(cls, name: str) -> type[Model]:
        """
        Unregister a previously added global scope.

        Parameters
        ----------
        name : str
            Name the scope was registered under.

        Returns
        -------
        type
            The model class, enabling fluent chaining.
        """
        cls.__meta__.global_scopes.pop(name, None)
        return cls

    @classmethod
    async def all(cls) -> Collection:
        """
        Retrieve every row of the model table.

        Returns
        -------
        Collection
            Collection of hydrated model instances.
        """
        return await cls.query().get()

    @classmethod
    async def find(cls, key: Any) -> Model | None:  # noqa: ANN401
        """
        Retrieve a model by its primary key.

        Parameters
        ----------
        key : Any
            Primary key value to look up.

        Returns
        -------
        Model or None
            Matching model, or ``None`` when absent.
        """
        return await cls.query().find(key)

    @classmethod
    async def findOrFail(cls, key: Any) -> Model:  # noqa: ANN401
        """
        Retrieve a model by primary key or raise when absent.

        Parameters
        ----------
        key : Any
            Primary key value to look up.

        Returns
        -------
        Model
            Matching model.

        Raises
        ------
        ModelNotFoundException
            If no record matches the key.
        """
        return await cls.query().findOrFail(key)

    @classmethod
    async def first(cls) -> Model | None:
        """
        Retrieve the first row of the model table.

        Returns
        -------
        Model or None
            First model, or ``None`` when the table is empty.
        """
        return await cls.query().first()

    @classmethod
    async def firstOrFail(cls) -> Model:
        """
        Retrieve the first row or raise when the table is empty.

        Returns
        -------
        Model
            First model.

        Raises
        ------
        ModelNotFoundException
            If the table has no rows.
        """
        return await cls.query().firstOrFail()

    @classmethod
    async def create(cls, attributes: dict[str, Any]) -> Model:
        """
        Create, persist, and return a new model.

        Parameters
        ----------
        attributes : dict
            Attributes to mass assign honoring the fillable rules.

        Returns
        -------
        Model
            Persisted model instance.

        Raises
        ------
        MassAssignmentException
            If an attribute violates the mass assignment rules.
        QueryException
            If the insert statement fails.
        """
        instance = cls(attributes)
        await instance.save()
        return instance

    @classmethod
    async def destroy(cls, *keys: Any) -> int:  # noqa: ANN401
        """
        Delete the models matching the given primary keys.

        Parameters
        ----------
        *keys : Any
            Primary key values to delete.

        Returns
        -------
        int
            Number of deleted rows.
        """
        if not keys:
            return 0
        return await cls.query().whereIn(cls.__meta__.primary_key, keys).delete()

    # ── Persistence ─────────────────────────────────────────────────────────

    async def save(self) -> bool:
        """
        Persist the model, inserting or updating as appropriate.

        New models are inserted, receiving their generated primary key;
        existing models write only their dirty attributes. Timestamps
        are maintained automatically when enabled, and the ``saving``,
        ``creating``/``updating``, ``created``/``updated`` and ``saved``
        events are dispatched around the write.

        Returns
        -------
        bool
            ``True`` when the operation succeeds or nothing changed,
            ``False`` when a listener vetoed the write.

        Raises
        ------
        QueryException
            If the statement fails to execute.
        """
        if not await self.fireEvent("saving"):
            return False

        exists = self._exists
        event = "updating" if exists else "creating"
        if not await self.fireEvent(event):
            return False

        saved = await self._performUpdate() if exists else await self._performInsert()

        await self.fireEvent("updated" if exists else "created")
        await self.fireEvent("saved")
        return saved

    async def update(self, attributes: dict[str, Any]) -> bool:
        """
        Mass assign the given attributes and persist the model.

        Parameters
        ----------
        attributes : dict
            Attributes to assign honoring the fillable rules.

        Returns
        -------
        bool
            ``True`` when the operation succeeds or nothing changed.

        Raises
        ------
        MassAssignmentException
            If an attribute violates the mass assignment rules.
        QueryException
            If the statement fails to execute.
        """
        self.fill(attributes)
        return await self.save()

    async def delete(self) -> bool:
        """
        Delete the model row, honoring soft deletes when enabled.

        Models declaring ``soft_deletes`` stamp their delete column
        instead of removing the row; every other model is deleted
        permanently.

        Returns
        -------
        bool
            ``True`` when a row was deleted or stamped, ``False`` for
            unsaved models or when a listener vetoed the operation.

        Raises
        ------
        QueryException
            If the statement fails to execute.
        """
        if not self._exists:
            return False
        if not await self.fireEvent("deleting"):
            return False

        meta = type(self).__meta__
        if meta.deleted_column is not None:
            deleted = await self._performSoftDelete(self.freshTimestamp())
        else:
            deleted = await self._performForceDelete()

        await self.fireEvent("deleted")
        return deleted

    async def _performForceDelete(self) -> bool:
        """
        Remove the persisted row permanently.

        Returns
        -------
        bool
            ``True`` when a row was removed.

        Raises
        ------
        QueryException
            If the statement fails to execute.
        """
        meta = type(self).__meta__
        plan = DeletePlan(
            table=meta.table,
            wheres=[
                WhereClause(
                    column=meta.primary_key,
                    value=self._primaryKeyValue(),
                ),
            ],
        )
        deleted = await self.getConnection().delete(plan)
        self._exists = False
        return deleted > 0

    # ── Timestamps ──────────────────────────────────────────────────────────

    @classmethod
    def freshTimestamp(cls) -> datetime:
        """
        Produce the current timestamp for persistence operations.

        Timezone-aware timestamps follow the selected update, creation,
        or soft-delete column's timezone option, naive UTC otherwise.

        Returns
        -------
        datetime
            Current UTC timestamp.
        """
        now = datetime.now(UTC)
        meta = cls.__meta__
        target = meta.updated_column or meta.created_column or meta.deleted_column
        if target is not None:
            column = meta.columns.get(target)
            aware = column is not None and column.timezone
            if not aware:
                return now.replace(tzinfo=None)
        return now

    @classmethod
    def newUniqueId(cls) -> Any:  # noqa: ANN401
        """
        Produce a client-generated primary key value.

        Overridable by models needing a different identifier scheme,
        such as ULIDs or prefixed keys.

        Returns
        -------
        Any
            Fresh unique identifier.
        """
        return uuid.uuid4()

    # ── Internal persistence helpers ────────────────────────────────────────

    def _primaryKeyValue(self) -> Any:  # noqa: ANN401
        """
        Return the primary key value identifying the stored row.

        The original value is preferred so a dirty primary key still
        targets the persisted row.

        Returns
        -------
        Any
            Primary key value.
        """
        key = type(self).__meta__.primary_key
        if key in self._original:
            return self._original[key]
        return self._attributes.get(key)

    async def _performInsert(self) -> bool:
        """
        Insert the model attributes as a new row.

        Returns
        -------
        bool
            ``True`` when the insert succeeds.

        Raises
        ------
        QueryException
            If the statement fails to execute.
        """
        meta = type(self).__meta__

        # Client-generated keys are produced before the row is written.
        if meta.uses_unique_ids and self._attributes.get(meta.primary_key) is None:
            self._attributes[meta.primary_key] = self.newUniqueId()

        # Maintain creation and update timestamps on first persist.
        timestamp_columns = (meta.created_column, meta.updated_column)
        timestamp = None
        for column in timestamp_columns:
            if column and column not in self._attributes:
                if timestamp is None:
                    timestamp = self.freshTimestamp()
                self._attributes[column] = timestamp

        values = serialize_for_storage(meta, self._attributes)
        plan = InsertPlan(table=meta.table, values=[values])
        result = await self.getConnection().insert(plan)

        # Adopt the database-generated primary key.
        generated = result.last_insert_id
        if meta.incrementing and generated is not None:
            self._attributes[meta.primary_key] = generated

        self._exists = True
        self._changes = deepcopy(self._attributes)
        self.syncOriginal()
        return True

    async def _performUpdate(self) -> bool:
        """
        Write the dirty attributes of an existing model.

        Returns
        -------
        bool
            ``True`` when a row was written or nothing changed,
            ``False`` when no stored row matched the primary key.

        Raises
        ------
        QueryException
            If the statement fails to execute.
        """
        dirty = self.getDirty()
        if not dirty:
            self._changes = {}
            return True

        meta = type(self).__meta__

        # Refresh the update timestamp alongside the dirty attributes.
        if meta.updated_column and meta.updated_column not in dirty:
            timestamp = self.freshTimestamp()
            self._attributes[meta.updated_column] = timestamp
            dirty[meta.updated_column] = timestamp

        plan = UpdatePlan(
            table=meta.table,
            values=serialize_for_storage(meta, dirty),
            wheres=[
                WhereClause(
                    column=meta.primary_key,
                    value=self._primaryKeyValue(),
                ),
            ],
        )
        affected = await self.getConnection().update(plan)

        if affected > 0:
            self._changes = deepcopy(dirty)
            self.syncOriginal()
        return affected > 0
