from types import MappingProxyType

CORE_APP_PATHS: MappingProxyType = MappingProxyType({
    "app": "app",
    "app_console": "app/console",
    "app_console_commands": "app/console/commands",
    "app_console_listeners": "app/console/listeners",
    "app_exceptions": "app/exceptions",
    "app_http": "app/http",
    "app_http_controllers": "app/http/controllers",
    "app_http_middleware": "app/http/middleware",
    "app_http_schemas": "app/http/schemas",
    "app_models": "app/models",
    "app_providers": "app/providers",
    "app_emails": "app/emails",
    "app_services": "app/services",
    "app_jobs": "app/jobs",
    "bootstrap": "bootstrap",
    "config": "config",
    "database": "database",
    "database_factories": "database/factories",
    "database_migrations": "database/migrations",
    "database_schemas": "database/schemas",
    "database_seeders": "database/seeders",
    "resources": "resources",
    "resources_css": "resources/css",
    "resources_js": "resources/js",
    "resources_lang": "resources/lang",
    "resources_views": "resources/views",
    "routes": "routes",
    "storage": "storage",
    "storage_app": "storage/app",
    "storage_app_private": "storage/app/private",
    "storage_app_public": "storage/app/public",
    "storage_framework": "storage/framework",
    "storage_logs": "storage/logs",
    "tests": "tests",
})
