from orionis.container.contracts.facade import IFacade
from orionis.http.routes.fluent import FluentRoute
from orionis.mcp.contracts.manager import IMcpManager
from orionis.mcp.server.primitives import Server

class Mcp(IFacade):
    @classmethod
    def getFacadeAccessor(cls) -> type[IMcpManager]: ...
    @staticmethod
    def web(path: str, server: type[Server]) -> FluentRoute: ...
    @staticmethod
    def local(name: str, server: type[Server]) -> None: ...
    @staticmethod
    async def toolsChanged(server: type[Server]) -> None: ...
    @staticmethod
    async def promptsChanged(server: type[Server]) -> None: ...
    @staticmethod
    async def resourcesChanged(server: type[Server]) -> None: ...
    @staticmethod
    async def resourceUpdated(server: type[Server], uri: str) -> None: ...
