name: Orionis Framework - Test Suite

on:
  push:
    branches:
      - 1.x
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🦀 Install uv
        uses: astral-sh/setup-uv@v3

      - name: 🐍 Set Python Version
        run: uv python install 3.14

      - name: 📦 Sync Dependencies
        run: uv sync

      - name: ⚡ Run Tests Aio [tests/aio]
        run: |
          uv run ruff check ./orionis/aio/ --statistics
          uv run python -B reactor test --start-dir="tests/aio" --verbosity=1 --fail-fast=1

      - name: ⏳ Run Tests Background [tests/background]
        run: |
          uv run ruff check ./orionis/background/ --statistics
          uv run python -B reactor test --start-dir="tests/background" --verbosity=1 --fail-fast=1

      - name: 💾 Run Tests Cache [tests/cache]
        run: |
          uv run ruff check ./orionis/cache/ --statistics
          uv run python -B reactor test --start-dir="tests/cache" --verbosity=1 --fail-fast=1

      - name: 🖥️ Run Tests Console [tests/console]
        run: |
          uv run ruff check ./orionis/console/ --statistics
          uv run python -B reactor test --start-dir="tests/console" --verbosity=1 --fail-fast=1

      - name: 🧩 Run Tests Container [tests/container]
        run: |
          uv run ruff check ./orionis/container/ --statistics
          uv run python -B reactor test --start-dir="tests/container" --verbosity=1 --fail-fast=1

      - name: 🔐 Run Tests Encrypter [tests/encrypter]
        run: |
          uv run ruff check ./orionis/encrypter/ --statistics
          uv run python -B reactor test --start-dir="tests/encrypter" --verbosity=1 --fail-fast=1

      - name: 🌍 Run Tests Environment [tests/environment]
        run: |
          uv run ruff check ./orionis/environment/ --statistics
          uv run python -B reactor test --start-dir="tests/environment" --verbosity=1 --fail-fast=1

      - name: 🚨 Run Tests Failure [tests/failure]
        run: |
          uv run ruff check ./orionis/failure/ --statistics
          uv run python -B reactor test --start-dir="tests/failure" --verbosity=1 --fail-fast=1

      - name: 📂 Run Tests Foundation [tests/foundation]
        run: |
          uv run ruff check ./orionis/foundation/ --statistics
          uv run python -B reactor test --start-dir="tests/foundation" --verbosity=1 --fail-fast=1

      - name: 🌐 Run Tests HTTP [tests/http]
        run: |
          uv run ruff check ./orionis/http/ --statistics
          uv run python -B reactor test --start-dir="tests/http" --verbosity=1 --fail-fast=1

      - name: 🔎 Run Tests Introspection [tests/introspection]
        run: |
          uv run ruff check ./orionis/introspection/ --statistics
          uv run python -B reactor test --start-dir="tests/introspection" --verbosity=1 --fail-fast=1

      - name: 🌎 Run Tests Localization [tests/localization]
        run: |
          uv run ruff check ./orionis/localization/ --statistics
          uv run python -B reactor test --start-dir="tests/localization" --verbosity=1 --fail-fast=1

      - name: 📝 Run Tests Logging [tests/logging]
        run: |
          uv run ruff check ./orionis/logging/ --statistics
          uv run python -B reactor test --start-dir="tests/logging" --verbosity=1 --fail-fast=1

      - name: 🏷️ Run Tests Metadata [tests/metadata]
        run: |
          uv run ruff check ./orionis/metadata/ --statistics
          uv run python -B reactor test --start-dir="tests/metadata" --verbosity=1 --fail-fast=1

      - name: 🗄️ Run Tests Database [tests/database]
        run: |
          uv run ruff check ./orionis/database/ --statistics
          uv run python -B reactor test --start-dir="tests/database" --verbosity=1 --fail-fast=1

      - name: 🧬 Run Tests ORM [tests/orm]
        run: |
          uv run ruff check ./orionis/orm/ --statistics
          uv run python -B reactor test --start-dir="tests/orm" --verbosity=1 --fail-fast=1

      - name: 📐 Run Tests Schemas [tests/schemas]
        run: |
          uv run ruff check ./orionis/schemas/ --statistics
          uv run python -B reactor test --start-dir="tests/schemas" --verbosity=1 --fail-fast=1

      - name: 🗂️ Run Tests Session [tests/session]
        run: |
          uv run ruff check ./orionis/session/ --statistics
          uv run python -B reactor test --start-dir="tests/session" --verbosity=1 --fail-fast=1

      - name: 🗃️ Run Tests Storage [tests/storage]
        run: |
          uv run ruff check ./orionis/storage/ --statistics
          uv run python -B reactor test --start-dir="tests/storage" --verbosity=1 --fail-fast=1

      - name: 🛠️ Run Tests Support [tests/support]
        run: |
          uv run ruff check ./orionis/support/ --statistics
          uv run python -B reactor test --start-dir="tests/support" --verbosity=1 --fail-fast=1

      - name: 🧪 Run Tests Test [tests/test]
        run: |
          uv run ruff check ./orionis/test/ --statistics
          uv run python -B reactor test --start-dir="tests/test" --verbosity=1 --fail-fast=1

      - name: 🖼️ Run Tests View [tests/view]
        run: |
          uv run ruff check ./orionis/view/ --statistics
          uv run python -B reactor test --start-dir="tests/view" --verbosity=1 --fail-fast=1

      - name: 📢 Running Tests with Uncontrolled Console Outputs
        run: |
          uv run python -B reactor test --file-pattern="excl_*.py" --verbosity=1 --fail-fast=1

      # - name: 🔍 Review Remaining Files
      #   run: |
      #     uv run ruff check ./orionis/mail/ --statistics
      #     uv run ruff check ./orionis/queues/ --statistics
