name: Orionis Framework - Test Suite

on:
  push:
    branches:
      - 1.x
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '17 7 * * 1'

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      PYTHONIOENCODING: utf-8
    timeout-minutes: 45

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🦀 Install uv
        uses: astral-sh/setup-uv@v3

      - name: 🐍 Set Python Version
        run: uv python install 3.14

      - name: 📦 Sync Dependencies
        run: uv sync

      - name: 🔍 Lint Orionis
        run: uv run ruff check ./orionis/ --statistics

      - name: ⚡ Run Tests Aio [tests/aio]
        run: |
          uv run python -B reactor test --start-dir="tests/aio" --verbosity=1 --fail-fast=1

      - name: 🔐 Run Tests Auth [tests/auth]
        run: |
          uv run python -B reactor test --start-dir="tests/auth" --verbosity=1 --fail-fast=1

      - name: ⏳ Run Tests Background [tests/background]
        run: |
          uv run python -B reactor test --start-dir="tests/background" --verbosity=1 --fail-fast=1

      - name: 💾 Run Tests Cache [tests/cache]
        run: |
          uv run python -B reactor test --start-dir="tests/cache" --verbosity=1 --fail-fast=1

      - name: 🖥️ Run Tests Console [tests/console]
        run: |
          uv run python -B reactor test --start-dir="tests/console" --verbosity=1 --fail-fast=1

      - name: 🧩 Run Tests Container [tests/container]
        run: |
          uv run python -B reactor test --start-dir="tests/container" --verbosity=1 --fail-fast=1

      - name: 🗄️ Run Tests Database [tests/database]
        run: |
          uv run python -B reactor test --start-dir="tests/database" --verbosity=1 --fail-fast=1

      - name: Run Durable Queue Tests
        run: uv run python -B reactor test --start-dir="tests/queues" --verbosity=1 --fail-fast=1

      - name: 🔐 Run Tests Encrypter [tests/encrypter]
        run: |
          uv run python -B reactor test --start-dir="tests/encrypter" --verbosity=1 --fail-fast=1

      - name: 🌍 Run Tests Environment [tests/environment]
        run: |
          uv run python -B reactor test --start-dir="tests/environment" --verbosity=1 --fail-fast=1

      - name: 🚨 Run Tests Failure [tests/failure]
        run: |
          uv run python -B reactor test --start-dir="tests/failure" --verbosity=1 --fail-fast=1

      - name: 📂 Run Tests Foundation [tests/foundation]
        run: |
          uv run python -B reactor test --start-dir="tests/foundation" --verbosity=1 --fail-fast=1

      - name: 🧮 Run Tests Hashing [tests/hashing]
        run: |
          uv run python -B reactor test --start-dir="tests/hashing" --verbosity=1 --fail-fast=1

      - name: 🌐 Run Tests HTTP [tests/http]
        run: |
          uv run python -B reactor test --start-dir="tests/http" --verbosity=1 --fail-fast=1

      - name: 🔎 Run Tests Introspection [tests/introspection]
        run: |
          uv run python -B reactor test --start-dir="tests/introspection" --verbosity=1 --fail-fast=1

      - name: 🌎 Run Tests Localization [tests/localization]
        run: |
          uv run python -B reactor test --start-dir="tests/localization" --verbosity=1 --fail-fast=1

      - name: 📝 Run Tests Logging [tests/logging]
        run: |
          uv run python -B reactor test --start-dir="tests/logging" --verbosity=1 --fail-fast=1

      - name: ✉️ Run Tests Mail [tests/mail]
        run: |
          uv run python -B reactor test --start-dir="tests/mail" --verbosity=1 --fail-fast=1

      - name: 🏷️ Run Tests Metadata [tests/metadata]
        run: |
          uv run python -B reactor test --start-dir="tests/metadata" --verbosity=1 --fail-fast=1

      - name: 🧬 Run Tests ORM [tests/orm]
        run: |
          uv run python -B reactor test --start-dir="tests/orm" --verbosity=1 --fail-fast=1

      - name: 📐 Run Tests Schemas [tests/schemas]
        run: |
          uv run python -B reactor test --start-dir="tests/schemas" --verbosity=1 --fail-fast=1

      - name: 🗂️ Run Tests Session [tests/session]
        run: |
          uv run python -B reactor test --start-dir="tests/session" --verbosity=1 --fail-fast=1

      - name: 🗃️ Run Tests Storage [tests/storage]
        run: |
          uv run python -B reactor test --start-dir="tests/storage" --verbosity=1 --fail-fast=1

      - name: 🛠️ Run Tests Support [tests/support]
        run: |
          uv run python -B reactor test --start-dir="tests/support" --verbosity=1 --fail-fast=1

      - name: 🧪 Run Tests Test [tests/test]
        run: |
          uv run python -B reactor test --start-dir="tests/test" --verbosity=1 --fail-fast=1

      - name: 🖼️ Run Tests View [tests/view]
        run: |
          uv run python -B reactor test --start-dir="tests/view" --verbosity=1 --fail-fast=1

      - name: 🧪 Run Root Tests [tests/test_example.py]
        run: |
          uv run python -B reactor test --start-dir="tests" --file-pattern="test_example.py" --verbosity=1 --fail-fast=1
